name: sms_otp_autofill
description: OTP Auto fill Support for Android Version 10 to 14.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  telephony: ^0.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
