name: sms_otp_autofill
description: SMS OTP Auto Fill is a Flutter package designed to simplify the process of handling OTP received via SMS.
version: 0.2.1
repository: https://github.com/TamilSelvanRaja/flutter_sms_otp_autofill.git

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
 
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
